#!/bin/bash
set -e

repo="carlsberg/gh-releaser"
tag="0.3.1"
exe="gh-releaser"
extensionPath="$(dirname "$0")"

if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
  mkdir -p "${extensionPath}/bin"
  rm -f "${extensionPath}/bin/*"
  gh release -R"${repo}" download "${tag}" -p "${exe}" --dir="${extensionPath}/bin"
  chmod +x "${extensionPath}/bin/${exe}"
fi

exec "${extensionPath}/bin/${exe}" "$@"