name: Jira Remote Links

on:
  issues:
    types: [opened, edited, deleted, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  sync:
    name: Jira Remote Links
    runs-on: ubuntu-latest
    steps:
      - uses: carlsberg/jira-remote-link-action@v1
        with:
          jira-url: ${{ secrets.JIRA_URL }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
